### ISSUE TITLE
e2e Docker Flow Improvements

### ISSUE THREAD

**Issue by aguzmant103** [bandada-infra/bandada#231]
- [ ] Test e2e running Bandada locally using docker files
- [ ] Tutorial to deploy Bandada on AWS or other cloud providers

**Comment by cijimenez** [comment]
Hello, what is the details about this issue?  @vplasencia @aguzmant103

**Comment by vplasencia** [comment]
Hey @cijimenez 

Thanks for asking. I will close this issue for now because this is something that should done in the future. 

The idea is to make sure that the Bandada infrastructure works fine locally with Docker and then write a tutorial on how to use Bandada and Docker locally and in production (different cloud providers).

Bandada is hosted using Docker and the idea is that people who prefer to save their information, can host the infrastructure themselves.
