### ISSUE TITLE
Improve user experience in the client app

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#270]
When you join a group via the invite link and click the Credential input text, the invite input is cleared.

**Comment by JoshdfG** [comment]
I would love to do this

**Comment by vplasencia** [comment]
Hey @JoshdfG! Sure. Do you want me to assign you this issue?

**Comment by antonyjaen** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bandada).

### My background and how it can be leveraged
Can I work on this ? 🙂

**Comment by jasonarias28** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bandada).

### My background and how it can be leveraged
I have 2 years of coding and learning about web development, recently I joined Dojo Coding to learn about web 3.0 and I think this will be a great opportunity to start contributing. 

### How I plan on tackling this issue
I would like to learn more about the issue and how can I improve the UX, I took online courses about UI/UX and I would like to apply what I learned on this issue.

**Comment by josephpdf** [comment]
Hi!, my name is Joseph Poveda.
I am a student of the Systems Programming degree, I am a recent member of the Dojo Coding community, where I am getting started in the world of Web3.
I have basic knowledge of different programming languages ​​and thanks to this I hope to be able to resolve the issue.
To approach this issue, I would investigate why the credential input field is clearing the invite link when clicked. First, I would review the component responsible for handling input states to ensure each input field maintains its own state without unintended interactions. Adjusting or isolating state management could resolve the issue. Additionally, testing the fix to confirm it prevents the invite input from clearing would be essential before completing the solution.

**Comment by bellodamilola** [comment]
Hi, I would love to pick this up.

**Comment by vplasencia** [comment]
Hey @bellodamilola! I just assigned the issue to you! Feel free to ask any questions you may have.

**Comment by bellodamilola** [comment]
Got it @vplasencia

**Comment by caxtonacollins** [comment]
I’d like to resolve this.

**Comment by System625** [comment]
Hello, I would love to work on this
I am able to clear invite input ensuring a smooth user experience

**Comment by bellodamilola** [comment]
Hey @vplasencia 

From the client codebase, I can see that a user can either join a group by invite code or by a credential group id. It is either one or the other.
Hence why the `invite code` input gets cleared when the `credential group Id` input is clicked. And also vice versa when the `invite code` input is clicked.

So for this case where the user joins via an invite link, what should the intended behaviour be? 

I propose this:

- When a user joins a group via an invite link with an `inviteCode`, the `credential group id` input gets disabled. This way, the `credential group id` input won't be clickable because the invite link carries the `inviteCode`. Hence the issue gets averted.
- Similarly, when the user joins a group with an invite link carrying a `credentialGroupId`, the `invite code` input gets disabled. Hence the issue gets averted. 

**Note: This input disabling will only happen when a user joins via an invite link.**

What are your thoughts @vplasencia ?

**Comment by vplasencia** [comment]
Hey @bellodamilola sounds great! Thank you very much for the ideas.

**Comment by kallis312** [comment]
I’d like to work on this.

I am very familiar with Javascript and Typescript framework such as Next.js, Svelte.js, Nuxt.
Also, I am very strongly with backend architecture

If given the opportunity, I would gladly participate.
And I can show perfect progress.

Best Regards

**Comment by vplasencia** [comment]
Hey @kallis312! Thank you very much for the interest. @bellodamilola had the issue assigned and just solved it. Feel free to pick any other open issue.
