### ISSUE TITLE
Docs: Add difference between the Bandada and Semaphore Groups in the FAQs

### ISSUE THREAD

**Issue by vplasencia** [bandada-infra/bandada#438]
## Resources

Bandada website: https://bandada.pse.dev/

Semaphore website: https://semaphore.pse.dev/

## Previous work

https://pse-team.notion.site/Bandada-vs-Semaphore-00d4bb92c9684bc0b1340301fc594dc9

**Comment by aguzmant103** [comment]
Some notes:

Regarding off-chain groups Semaphore has libraries to make it easier to have an infrastructure to manage groups. Semaphore does not have an infrastructure to manage off-chain groups. Bandada has that and also with other features such as: invite code (or link) to join a group and antisybil mechanisms to join a group.

Regarding on-chain groups, Semaphore has a set of on-chain contracts to manage groups so I would say that it can manage on-chain groups well.

In general:
- Semaphore is a protocol for anonymous interactions. It should be simple.
- Bandada is an infrastructure to manage privacy-preserving groups.
- Bandada and Semaphore are compatible, the groups are different but can be transferred from one project to the other and used together.
- Bandada makes it easier to work with off-chain Semaphore groups since Semaphore does not have an infrastructure for that.
- To join a Semaphore group sometimes you need an antisybil mechanism, Bandada has this functionality integrated.
- Bandada will help to manage really large groups because when a group has too many members it's necessary to create the merkle proof in a server instead of in the client side (browser).
- Bandada implements easily the gating mechanisms to join groups.
- Bandada makes these gating mechanisms composable (using logical operators) expanding the expressivity to join the group

**Comment by vplasencia** [comment]
Hey @od-hunter! Yes, it's still open. I just assigned you the issue. Feel free to ask any questions you may have.

**Comment by od-hunter** [comment]
Thank you @vplasencia

**Comment by od-hunter** [comment]
@vplasencia, 
Is it the [faq.md](https://github.com/bandada-infra/bandada/blob/main/apps/docs/docs/faq.md) am expected to add the update for the differences?

**Comment by od-hunter** [comment]
Hello @vplasencia please review my pr

**Comment by vplasencia** [comment]
Hey @od-hunter! This is a high priority task now, so I will work on it to finish it asap. 

Then I will need to close your PR, sorry for it, but feel free to ask for any other `good first issue` here: https://github.com/bandada-infra/bandada/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

Thank you! 🙏
